# -*- coding: utf-8 -*-
"""DS-Exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cfwwUQbnHyG_SaIdkpPx8ope9o0btFl
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

df = pd.read_csv("/content/drive/MyDrive/Data Science/Data_set.csv")
df

print("Dataset Information")
df.info()

print("\nStatistical Summary")
print(df.describe(include='all'))

print("\nFirst 5 Rows")
print(df.head())

print("\nLast 5 Rows")
print(df.tail())

print("Null Values")
print(df.isnull())

print("\nNull Count")
print(df.isnull().sum())

print("\nAfter Dropping Null Values")
print(df.dropna())

print("\nFill Null Values with 'O'")
print(df.fillna("O"))

print("\nForward Fill")
print(df.fillna(method="ffill"))

print("\nBackward Fill")
print(df.fillna(method="bfill"))

mean_df = df.copy()

numeric_columns = mean_df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    mean_df[col].fillna(mean_df[col].mean(), inplace=True)

print(mean_df)

print("\nAfter Dropping Remaining Null Values")
print(mean_df.dropna())

age = [1,3,28,27,25,92,30,39,40,50,26,24,29,94]
af = pd.DataFrame(age, columns=["Age"])

sns.boxplot(y=af["Age"])
plt.title("Before Removing Outliers")
plt.show()

Q1 = af["Age"].quantile(0.25)
Q3 = af["Age"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower Limit:", lower)
print("Upper Limit:", upper)

outliers = af[(af["Age"] < lower) | (af["Age"] > upper)]

print("\nOutliers")
print(outliers)

af_clean = af[(af["Age"] >= lower) & (af["Age"] <= upper)]

print("\nAfter Removing Outliers")
print(af_clean)

sns.boxplot(y=af_clean["Age"])
plt.title("After Removing Outliers")
plt.show()

data = [1,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,96,99,158]

df2 = pd.DataFrame(data, columns=["Data"])

sns.boxplot(y=df2["Data"])
plt.title("Before Removing Outliers")
plt.show()

z = np.abs(stats.zscore(df2["Data"]))

print("Z Scores")
print(z)

outliers = df2[z > 3]

print("\nOutliers")
print(outliers)

df2_clean = df2[z <= 3]

print("\nAfter Removing Outliers")
print(df2_clean)

sns.boxplot(y=df2_clean["Data"])
plt.title("After Removing Outliers")
plt.show()